// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: safe.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SafeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SafeRoot : GPBRootObject
@end

#pragma mark - RegisterData

typedef GPB_ENUM(RegisterData_FieldNumber) {
  RegisterData_FieldNumber_Version = 1,
  RegisterData_FieldNumber_AdminAddress = 2,
  RegisterData_FieldNumber_AppName = 3,
  RegisterData_FieldNumber_AppDesc = 4,
  RegisterData_FieldNumber_DevType = 5,
  RegisterData_FieldNumber_DevName = 6,
  RegisterData_FieldNumber_WebURL = 7,
  RegisterData_FieldNumber_LogoURL = 8,
  RegisterData_FieldNumber_CoverURL = 9,
};

@interface RegisterData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *adminAddress;
/** Test to see if @c adminAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAdminAddress;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *appName;
/** Test to see if @c appName has been set. */
@property(nonatomic, readwrite) BOOL hasAppName;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *appDesc;
/** Test to see if @c appDesc has been set. */
@property(nonatomic, readwrite) BOOL hasAppDesc;

/** uint8_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *devType;
/** Test to see if @c devType has been set. */
@property(nonatomic, readwrite) BOOL hasDevType;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *devName;
/** Test to see if @c devName has been set. */
@property(nonatomic, readwrite) BOOL hasDevName;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *webURL;
/** Test to see if @c webURL has been set. */
@property(nonatomic, readwrite) BOOL hasWebURL;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *logoURL;
/** Test to see if @c logoURL has been set. */
@property(nonatomic, readwrite) BOOL hasLogoURL;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *coverURL;
/** Test to see if @c coverURL has been set. */
@property(nonatomic, readwrite) BOOL hasCoverURL;

@end

#pragma mark - AuthData

typedef GPB_ENUM(AuthData_FieldNumber) {
  AuthData_FieldNumber_Version = 1,
  AuthData_FieldNumber_SetType = 2,
  AuthData_FieldNumber_AdminAddress = 3,
  AuthData_FieldNumber_UserAddress = 4,
  AuthData_FieldNumber_Auth = 5,
};

@interface AuthData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** uint8_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *setType;
/** Test to see if @c setType has been set. */
@property(nonatomic, readwrite) BOOL hasSetType;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *adminAddress;
/** Test to see if @c adminAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAdminAddress;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *userAddress;
/** Test to see if @c userAddress has been set. */
@property(nonatomic, readwrite) BOOL hasUserAddress;

/** uint32_t */
@property(nonatomic, readwrite) uint32_t auth;

@property(nonatomic, readwrite) BOOL hasAuth;
@end

#pragma mark - ExtendData

typedef GPB_ENUM(ExtendData_FieldNumber) {
  ExtendData_FieldNumber_Version = 1,
  ExtendData_FieldNumber_Auth = 2,
  ExtendData_FieldNumber_ExtendData = 3,
};

@interface ExtendData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** uinit32_t */
@property(nonatomic, readwrite) uint32_t auth;

@property(nonatomic, readwrite) BOOL hasAuth;
/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *extendData;
/** Test to see if @c extendData has been set. */
@property(nonatomic, readwrite) BOOL hasExtendData;

@end

#pragma mark - IssueData

typedef GPB_ENUM(IssueData_FieldNumber) {
  IssueData_FieldNumber_Version = 1,
  IssueData_FieldNumber_ShortName = 2,
  IssueData_FieldNumber_AssetName = 3,
  IssueData_FieldNumber_AssetDesc = 4,
  IssueData_FieldNumber_AssetUnit = 5,
  IssueData_FieldNumber_TotalAmount = 6,
  IssueData_FieldNumber_FirstIssueAmount = 7,
  IssueData_FieldNumber_FirstActualAmount = 8,
  IssueData_FieldNumber_Decimals = 9,
  IssueData_FieldNumber_Destory = 10,
  IssueData_FieldNumber_PayCandy = 11,
  IssueData_FieldNumber_CandyAmount = 12,
  IssueData_FieldNumber_CandyExpired = 13,
  IssueData_FieldNumber_Remarks = 14,
};

@interface IssueData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *shortName;
/** Test to see if @c shortName has been set. */
@property(nonatomic, readwrite) BOOL hasShortName;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetName;
/** Test to see if @c assetName has been set. */
@property(nonatomic, readwrite) BOOL hasAssetName;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetDesc;
/** Test to see if @c assetDesc has been set. */
@property(nonatomic, readwrite) BOOL hasAssetDesc;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetUnit;
/** Test to see if @c assetUnit has been set. */
@property(nonatomic, readwrite) BOOL hasAssetUnit;

/** int64_t */
@property(nonatomic, readwrite) int64_t totalAmount;

@property(nonatomic, readwrite) BOOL hasTotalAmount;
/** int64_t */
@property(nonatomic, readwrite) int64_t firstIssueAmount;

@property(nonatomic, readwrite) BOOL hasFirstIssueAmount;
/** int64_t */
@property(nonatomic, readwrite) int64_t firstActualAmount;

@property(nonatomic, readwrite) BOOL hasFirstActualAmount;
/** uint8_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *decimals;
/** Test to see if @c decimals has been set. */
@property(nonatomic, readwrite) BOOL hasDecimals;

/** bool */
@property(nonatomic, readwrite) BOOL destory;

@property(nonatomic, readwrite) BOOL hasDestory;
/** bool */
@property(nonatomic, readwrite) BOOL payCandy;

@property(nonatomic, readwrite) BOOL hasPayCandy;
/** int64_t */
@property(nonatomic, readwrite) int64_t candyAmount;

@property(nonatomic, readwrite) BOOL hasCandyAmount;
/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *candyExpired;
/** Test to see if @c candyExpired has been set. */
@property(nonatomic, readwrite) BOOL hasCandyExpired;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *remarks;
/** Test to see if @c remarks has been set. */
@property(nonatomic, readwrite) BOOL hasRemarks;

@end

#pragma mark - CommonData

typedef GPB_ENUM(CommonData_FieldNumber) {
  CommonData_FieldNumber_Version = 1,
  CommonData_FieldNumber_AssetId = 2,
  CommonData_FieldNumber_Amount = 3,
  CommonData_FieldNumber_Remarks = 4,
};

/**
 * add issue, transfer, issue change
 **/
@interface CommonData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** uint256 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetId;
/** Test to see if @c assetId has been set. */
@property(nonatomic, readwrite) BOOL hasAssetId;

/** int64_t */
@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) BOOL hasAmount;
/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *remarks;
/** Test to see if @c remarks has been set. */
@property(nonatomic, readwrite) BOOL hasRemarks;

@end

#pragma mark - PutCandyData

typedef GPB_ENUM(PutCandyData_FieldNumber) {
  PutCandyData_FieldNumber_Version = 1,
  PutCandyData_FieldNumber_AssetId = 2,
  PutCandyData_FieldNumber_Amount = 3,
  PutCandyData_FieldNumber_Expired = 4,
  PutCandyData_FieldNumber_Remarks = 5,
};

@interface PutCandyData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** uint256 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetId;
/** Test to see if @c assetId has been set. */
@property(nonatomic, readwrite) BOOL hasAssetId;

/** int64_t */
@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) BOOL hasAmount;
/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *expired;
/** Test to see if @c expired has been set. */
@property(nonatomic, readwrite) BOOL hasExpired;

/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *remarks;
/** Test to see if @c remarks has been set. */
@property(nonatomic, readwrite) BOOL hasRemarks;

@end

#pragma mark - GetCandyData

typedef GPB_ENUM(GetCandyData_FieldNumber) {
  GetCandyData_FieldNumber_Version = 1,
  GetCandyData_FieldNumber_AssetId = 2,
  GetCandyData_FieldNumber_Amount = 3,
  GetCandyData_FieldNumber_Remarks = 4,
};

@interface GetCandyData : GPBMessage

/** uint16_t */
@property(nonatomic, readwrite, copy, null_resettable) NSData *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

/** uint256 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *assetId;
/** Test to see if @c assetId has been set. */
@property(nonatomic, readwrite) BOOL hasAssetId;

/** int64_t */
@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) BOOL hasAmount;
/** string */
@property(nonatomic, readwrite, copy, null_resettable) NSData *remarks;
/** Test to see if @c remarks has been set. */
@property(nonatomic, readwrite) BOOL hasRemarks;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
